### ISSUE TITLE
Editing Session.hostname after creation has no effect

### ISSUE THREAD

**Issue by BYT3M3** [easysnmp/easysnmp#100]
So this issue is probably just part of the semantics of a session, by which I mean the idea would be you have to create a new session if you wish to connect to a different host. But it wasn't obvious to me that I can't just edit the hostname of the session to change the host. Maybe this should be clarified in the documentation?

**Comment by kamakazikamikaze** [comment]
Agreed. This is an important detail and should be added. Thank you for bringing this to my attention.

**Comment by kamakazikamikaze** [comment]
e75aabf introduces a new method for re-creating the underlying Net-SNMP session object in case you want to update session parameters. Documentation has been updated to reflect the changes. `v0.2.6a2` or `v0.2.6` will include these changes.
