### ISSUE TITLE
asyncio awaitable perferomance

### ISSUE THREAD

**Issue by agn-7** [easysnmp/easysnmp#109]
I'm using `easysnmp` to read from SNMP devices in _Python 3.6_.
Now I want using it with asynchronous capability.

Is any approach to use `easysnmp` as a awaitable method?

Here's my simplified snippet code for better sense:

```
import time
import asyncio
from easysnmp import snmp_get
from pprint import pprint

async def read(**kwargs):
    oid = kwargs.get('oid', '0.0.0.0.0.0')
    name = kwargs.get('tag_name', 'Default Name')
    address = kwargs.get('address', 1)
    community = kwargs.get('community', 'public')
    version = kwargs.get('version', 1)
    port = kwargs.get('port', 161)
    timeout = kwargs.get('timeout', 1)
    retries = kwargs.get('retries', 3)
    interval = kwargs.get('sleep_time', 3)
    data = None
    tick = time.time()

    try:
        data = float(
            snmp_get(  # TODO :: Check the await at here.
                oid,
                hostname=address,
                community=community,
                version=version,
                remote_port=port,
                timeout=timeout,
                retries=retries,
            ).value
        )
    except:
        data = -8555
    finally:
        tack = time.time() - tick
        result = {
            'time': datetime.now().strftime('%Y-%m-%dT%H:%M:%S'),
            'data': {name: data}
        }
        pprint(result)

        if interval >= (retries * timeout):
            await asyncio.sleep(interval - tack)
        else:
            await asyncio.sleep(interval)

async def read_forever(**kwargs):
    while True:
        await read(**kwargs)

def init_loop(configs):
    loop = asyncio.get_event_loop()
    futures = [asyncio.ensure_future(read_forever(**conf)) for conf in configs]
    # futures = [loop.create_task(read_forever(**conf)) for conf in configs]

    return loop

configs = [  #  DUMMY
 {"name": "ups", "address": "192.168.1.120", "port": 161, "timeout": 1,
  "retries": 3, "community": "public", "version": 2, "sleep_time": 5,
  "tag_name": "battery_current", "oid": "1.3.6.1.2.1.33.1.4.2.0"},

 {"name": "Switch2960", "address": "192.168.1.2", "port": 161, "timeout": 1,
  "retries": 3, "community": "public", "version": 1, "sleep_time": 4,
  "tag_name": "PortStatus1", "oid": "1.3.6.1.2.1.2.2.1.8.10001"}
]

loop = init_loop(configs)

try:
    loop.run_forever()

except KeyboardInterrupt:
    pass

finally:
    print("Closing Loop")
```

The above code works asynchronous with a single thread (it benefits from `await asyncio.sleep(interval)` gap time).

### But the problem is that, when `snmp_get()` has been a bad `oid` or bad connection it caused a timeout.
 
This interruption will cause me to lose a series of continuous data with the defined time interval.

### I think If `snmp_get()` was awaitable I can overcome it with such as the following:

`await snmp_get(...).value`

How can I fix this issue?

**Comment by kamakazikamikaze** [comment]
While I've had to work with async/await in other projects, I'm afraid that I'm not familiar with the underlying mechanics of it and what it takes to make a C Extension compatible with asyncio. This may need to be a feature request or even a separate package/release depending on what's required to get the Net-SNMP library to work with it.

**Comment by agn-7** [comment]
That's right. I released  `snmp_get()` is not an awaitable method right now. So I had to use [pysnmp](https://github.com/etingof/pysnmp) instead.

**Comment by kamakazikamikaze** [comment]
Sorry to hear that the project couldn't fulfill your requirements but I am glad that a solution already exists to help you do what you need. Best of luck to you!
