### ISSUE TITLE
net-snmp-config.h: No such file or directory

### ISSUE THREAD

**Issue by NicolasPaquetQI** [easysnmp/easysnmp#110]
Hi im a beginner and I have a error of file not found when im running  pip install  similar to the issue #67 but the Net-SNMP package is installed : 

root@zabbix-app:/ # pip install easysnmp
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting easysnmp
  Using cached https://files.pythonhosted.org/packages/e0/6f/2fd5c9113a488c81aa95f9006744c6998878a80135010f87506638ba6d5c/easysnmp-0.2.5.tar.gz
Installing collected packages: easysnmp
  Running setup.py install for easysnmp ... error
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-DLYIEO/easysnmp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ZMVxjP/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7
    creating build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/__init__.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/compat.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/easy.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/exceptions.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/helpers.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/session.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/utils.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    copying easysnmp/variables.py -> build/lib.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    running build_ext
    building 'easysnmp.interface' extension
    creating build/temp.freebsd-11.1-RELEASE-p1-amd64-2.7
    creating build/temp.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -I/usr/local/include/python2.7 -c easysnmp/interface.c -o build/temp.freebsd-11.1-RELEASE-p1-amd64-2.7/easysnmp/interface.o -Wno-unused-function
    easysnmp/interface.c:24:10: fatal error: 'net-snmp/net-snmp-config.h' file not found
    #include <net-snmp/net-snmp-config.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-DLYIEO/easysnmp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ZMVxjP/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-DLYIEO/easysnmp/

__________________________________________________________________________________________________________

The file is there for what I can see : 

root@zabbix-app:/ # find / -type f -print | grep 'net-snmp-config.h'
/usr/local/include/net-snmp/net-snmp-config.h
/usr/ports/net-mgmt/net-snmp/files/patch-include__net-snmp__net-snmp-config.h.in
/usr/ports/net-mgmt/net-snmp/work/net-snmp-5.7.3/include/net-snmp/net-snmp-config.h.in
/usr/ports/net-mgmt/net-snmp/work/net-snmp-5.7.3/include/net-snmp/net-snmp-config.h.in.orig
/usr/ports/net-mgmt/net-snmp/work/net-snmp-5.7.3/include/net-snmp/net-snmp-config.h
/usr/ports/net-mgmt/net-snmp/work/net-snmp-5.7.3/include/net-snmp/net-snmp-config.h.bak
/usr/ports/net-mgmt/net-snmp/work/net-snmp-5.7.3/win32/net-snmp/net-snmp-config.h.in
/usr/ports/net-mgmt/net-snmp/work/net-snmp-5.7.3/win32/net-snmp/net-snmp-config.h
/usr/ports/net-mgmt/net-snmp/work/stage/usr/local/include/net-snmp/net-snmp-config.h

OS : FreeBSD 11.1-RELEASE-p1
net-snmp : 5.7.3
Python : 2.7

Do you guys have an idea of what can cause this issue ?
 Thanks you very much for your work and help !

**Comment by 0x657674** [comment]
Hello,
I had the same problem and it was due to not having the net-snmp-devel package installed:

$ sudo yum install net-snmp-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo1.ash.innoscale.net
 * extras: mirror.ash.fastserv.com
 * updates: ewr.edge.kernel.org
Resolving Dependencies
....
$ pip install easysnmp
Collecting easysnmp
  Using cached https://files.pythonhosted.org/packages/e0/6f/2fd5c9113a488c81aa95f9006744c6998878a80135010f87506638ba6d5c/easysnmp-0.2.5.tar.gz
Installing collected packages: easysnmp
  Running setup.py install for easysnmp ... done
Successfully installed easysnmp-0.2.5

**Comment by NicolasPaquetQI** [comment]
Thank you for your help.I think you're right but according to my research, net-snmp-devel library is not supported with FreeBSD.I probably will have to do without easysnmp for my code :( Thanks anyway!
