### ISSUE TITLE
New release with recent improvements?

### ISSUE THREAD

**Issue by amotl** [easysnmp/easysnmp#147]
Dear Kent,

first things first: Thanks a stack for conceiving and maintaining this excellent library. We recently switched to `easysnmp` within the [`check_synology`] project by @wernerfred, on behalf of https://github.com/wernerfred/check_synology/pull/19 which was originally contributed by @kainhofer. It brought huge efficiency gains to the code base which is very important because those programs are executed very often, sometimes also on machines with constrained resources.

Now, we just improved the robustness with https://github.com/wernerfred/check_synology/pull/30 and would really be happy to be able to build upon the improvements by @uedvt359 coming from #129, in order to mitigate #108.

In that spirit, may we humbly ask you to publish a new release to PyPI? It would make so many lifes easier. In the very same spirit, we would like to thank you again for giving the project some love just recently and also send kudos to the other contributors who submitted important patches.

Thank you in advance and with kind regards,
Andreas.

[`check_synology`]: https://github.com/wernerfred/check_synology

**Comment by kamakazikamikaze** [comment]
EDIT

Sorry, I didn't double-check the items you were citing and was thinking of a different issue and merge request.

I'll look to see about a new PyPi release. My apologies, I'm juggling too much and continue to focus too much on one project while neglecting others.

**Comment by kamakazikamikaze** [comment]
Working on a Github Action today for generating a new release. Hopefully I can get it to work by the end of the day.

**Comment by kamakazikamikaze** [comment]
Couldn't get past the issue regarding wheels with `linux_x86_64` in the name and I forgot that removing uploaded packages is completely irreversible.

Asinine decisions aside, the source is available at https://pypi.org/project/easysnmp/0.2.6a0/#files but installing via `pip` currently does not work. I'll just bite the bullet and release the project as 0.2.6 or 0.2.6a1 so it'll play nice with the CLI.

**Comment by kamakazikamikaze** [comment]
Ok, CI/CD process for wheel generation and publication is now complete. Version `0.2.6a1` is uploaded to PyPi. You will probably need to use `pip install --upgrade easysnmp==0.2.6a1` in order to install since it's marked as "pre-release". Let me know if you run into any issues.

**Comment by joseftschiggerlnts** [comment]
Hey @kamakazikamikaze 
I was just checking 0.2.6a and 0.2.6a1, it doesn't include the new "update_session" function, right? 
Any chance we could have that included in a further release anytime soon please? 

Thanks :)

**Comment by kamakazikamikaze** [comment]
@joseftschiggerlnts I'll go ahead and move to an official release in the near future instead of the staggered beta releases since my time is getting split into many different directions again.

**Comment by joseftschiggerlnts** [comment]
That would be perfect, thank you @kamakazikamikaze

**Comment by kamakazikamikaze** [comment]
@joseftschiggerlnts Finally released. Please check it out and let me know if anything isn't working.

**Comment by joseftschiggerlnts** [comment]
Perfect! Thank you :)

**Comment by amotl** [comment]
Dear Kent,

thank you very much for your efforts on releasing version 0.2.6. I've just updated https://github.com/wernerfred/check_synology/pull/30 to reflect this matter.

Keep up the spirit and with kind regards,
Andreas.
