### ISSUE TITLE
[Question] Can not install directly from github

### ISSUE THREAD

**Issue by joseftschiggerlnts** [easysnmp/easysnmp#155]
Hey,

I try to install easysnmp directly from github as I need a feature/function not currently available as pip package.
`pip3.10 install git+https://github.com/kamakazikamikaze/easysnmp.git@f43e029aabc0f0906d759a603eeb49cb5db569ab`
This gives me the following output:

`Collecting git+https://github.com/kamakazikamikaze/easysnmp.git@f43e029aabc0f0906d759a603eeb49cb5db569ab
  Cloning https://github.com/kamakazikamikaze/easysnmp.git (to revision f43e029aabc0f0906d759a603eeb49cb5db569ab) to /private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-req-build-_jw98a_3
  Running command git clone --filter=blob:none --quiet https://github.com/kamakazikamikaze/easysnmp.git /private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-req-build-_jw98a_3
  Running command git rev-parse -q --verify 'sha^f43e029aabc0f0906d759a603eeb49cb5db569ab'
  Running command git fetch -q https://github.com/kamakazikamikaze/easysnmp.git f43e029aabc0f0906d759a603eeb49cb5db569ab
  Resolved https://github.com/kamakazikamikaze/easysnmp.git to commit f43e029aabc0f0906d759a603eeb49cb5db569ab
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running egg_info
      creating /private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-pip-egg-info-0vd7jh_g/easysnmp.egg-info
      writing /private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-pip-egg-info-0vd7jh_g/easysnmp.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-pip-egg-info-0vd7jh_g/easysnmp.egg-info/dependency_links.txt
      writing top-level names to /private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-pip-egg-info-0vd7jh_g/easysnmp.egg-info/top_level.txt
      writing manifest file '/private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-pip-egg-info-0vd7jh_g/easysnmp.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-pip-egg-info-0vd7jh_g/easysnmp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-pip-egg-info-0vd7jh_g/easysnmp.egg-info/SOURCES.txt'
      error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so (No such file or directory)
      Usage: /Library/Developer/CommandLineTools/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/wp/gx88m1xx1lndrlghfh14h8jw0000gp/T/pip-req-build-_jw98a_3/setup.py", line 177, in <module>
          _ = check_output(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'install_name_tool -change  /usr/local/opt/net-snmp/lib/libnetsnmp.40.dylib build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

I am on macOS Monterey 12.4 and python 3.10.
Anyone else having this problem?

Thanks! :)

**Comment by kamakazikamikaze** [comment]
> `install_name_tool -change /usr/local/opt/net-snmp/lib/libnetsnmp.40.dylib build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so`

This is missing an item. Do you have net-snmp installed via `brew`?

**Comment by joseftschiggerlnts** [comment]
Yes, I do.

test@CEASDFEEFFE ~ % brew list net-snmp
/usr/local/Cellar/net-snmp/5.9.1/bin/agentxtrap
/usr/local/Cellar/net-snmp/5.9.1/bin/checkbandwidth
/usr/local/Cellar/net-snmp/5.9.1/bin/encode_keychange
/usr/local/Cellar/net-snmp/5.9.1/bin/fixproc
/usr/local/Cellar/net-snmp/5.9.1/bin/ipf-mod.pl
/usr/local/Cellar/net-snmp/5.9.1/bin/mib2c
/usr/local/Cellar/net-snmp/5.9.1/bin/mib2c-update
/usr/local/Cellar/net-snmp/5.9.1/bin/net-snmp-cert
/usr/local/Cellar/net-snmp/5.9.1/bin/net-snmp-config
/usr/local/Cellar/net-snmp/5.9.1/bin/net-snmp-create-v3-user
/usr/local/Cellar/net-snmp/5.9.1/bin/snmp-bridge-mib
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpbulkget
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpbulkwalk
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpcheck
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpconf
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpdelta
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpdf
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpget
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpgetnext
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpinform
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpnetstat
/usr/local/Cellar/net-snmp/5.9.1/bin/snmppcap
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpping
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpps
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpset
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpstatus
/usr/local/Cellar/net-snmp/5.9.1/bin/snmptable
/usr/local/Cellar/net-snmp/5.9.1/bin/snmptest
/usr/local/Cellar/net-snmp/5.9.1/bin/snmptop
/usr/local/Cellar/net-snmp/5.9.1/bin/snmptranslate
/usr/local/Cellar/net-snmp/5.9.1/bin/snmptrap
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpusm
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpvacm
/usr/local/Cellar/net-snmp/5.9.1/bin/snmpwalk
/usr/local/Cellar/net-snmp/5.9.1/bin/tkmib
/usr/local/Cellar/net-snmp/5.9.1/bin/traptoemail
/usr/local/Cellar/net-snmp/5.9.1/include/net-snmp/ (184 files)
/usr/local/Cellar/net-snmp/5.9.1/lib/libnetsnmp.40.dylib
/usr/local/Cellar/net-snmp/5.9.1/lib/libnetsnmpagent.40.dylib
/usr/local/Cellar/net-snmp/5.9.1/lib/libnetsnmphelpers.40.dylib
/usr/local/Cellar/net-snmp/5.9.1/lib/libnetsnmpmibs.40.dylib
/usr/local/Cellar/net-snmp/5.9.1/lib/libnetsnmptrapd.40.dylib
/usr/local/Cellar/net-snmp/5.9.1/lib/pkgconfig/ (2 files)
/usr/local/Cellar/net-snmp/5.9.1/lib/ (10 other files)
/usr/local/Cellar/net-snmp/5.9.1/sbin/snmpd
/usr/local/Cellar/net-snmp/5.9.1/sbin/snmptrapd
/usr/local/Cellar/net-snmp/5.9.1/share/man/ (134 files)
/usr/local/Cellar/net-snmp/5.9.1/share/snmp/ (174 files)

**Comment by kamakazikamikaze** [comment]
Ok, then we're entering a point where our environments diverge. So bear with me.

I need you to clone the repo to a folder to ensure persistence as we troubleshoot this. Once you've done that, run `python setup.py install`. After it fails, run this command and paste the output in a new comment:
`otool -L build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so`

**Comment by joseftschiggerlnts** [comment]
test@C02DG9X7MD6R test % git clone https://github.com/kamakazikamikaze/easysnmp.git
Cloning into 'easysnmp'...
remote: Enumerating objects: 1570, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1570 (delta 0), reused 1 (delta 0), pack-reused 1564
Receiving objects: 100% (1570/1570), 650.77 KiB | 5.51 MiB/s, done.
Resolving deltas: 100% (935/935), done.
test@C02DG9X7MD6R test % cd easysnmp 
test@C02DG9X7MD6R easysnmp % python3.10 setup.py install
/Users/test/Downloads/test/easysnmp/setup.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils import sysconfig
/Users/test/Downloads/test/easysnmp/setup.py:5: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils import sysconfig
running install
running bdist_egg
running egg_info
creating easysnmp.egg-info
writing easysnmp.egg-info/PKG-INFO
writing dependency_links to easysnmp.egg-info/dependency_links.txt
writing top-level names to easysnmp.egg-info/top_level.txt
writing manifest file 'easysnmp.egg-info/SOURCES.txt'
reading manifest file 'easysnmp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'easysnmp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-universal2/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.9-universal2-3.10
creating build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/compat.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/variables.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/session.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/__init__.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/easy.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/utils.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/exceptions.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
copying easysnmp/helpers.py -> build/lib.macosx-10.9-universal2-3.10/easysnmp
running build_ext
building 'easysnmp.interface' extension
creating build/temp.macosx-10.9-universal2-3.10
creating build/temp.macosx-10.9-universal2-3.10/easysnmp
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/usr/local/opt/net-snmp/include -I/usr/local/opt/openssl@1.1/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c easysnmp/interface.c -o build/temp.macosx-10.9-universal2-3.10/easysnmp/interface.o
In file included from easysnmp/interface.c:48:
easysnmp/simple_bitarray.h:116:29: warning: variable 'nbytes' is used uninitialized whenever 'for' loop exits because its condition is false [-Wsometimes-uninitialized]
            for (i = nbits; i > (nbits - remaining_bits); i--)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/simple_bitarray.h:122:27: note: uninitialized use occurs here
        memset(&ba[1], 0, nbytes);
                          ^~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:77:33: note: expanded from macro 'memset'
                __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                              ^~~~~~~~~~~
easysnmp/simple_bitarray.h:116:29: note: remove the condition if it is always true
            for (i = nbits; i > (nbits - remaining_bits); i--)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/simple_bitarray.h:98:22: note: initialize the variable 'nbytes' to silence this warning
        size_t nbytes;
                     ^
                      = 0
easysnmp/interface.c:500:21: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
            if (len > buf_len)
                ~~~ ^ ~~~~~~~
easysnmp/interface.c:1260:40: warning: comparison of integers of different signs: 'unsigned long' and 'long' [-Wsign-compare]
                else if (last_errindex > (*response)->errindex)
                         ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:2407:55: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
        if (snmp_version == 1 && DEFAULT_NUM_BAD_OIDS < varlist_len)
                                 ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~
easysnmp/interface.c:2894:44: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                    if ((vars->name_length < oid_arr_len[varlist_ind]) ||
                         ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:3650:48: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                        if ((vars->name_length < oid_arr_len[varlist_ind]) ||
                             ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:3975:28: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'unsigned long' [-Wsign-compare]
                if (tmplen >= sizeof(tmp_val_str))
                    ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:4152:5: warning: variable 'pval' is used uninitialized whenever switch default is taken [-Wsometimes-uninitialized]
    default:
    ^~~~~~~
easysnmp/interface.c:4158:16: note: uninitialized use occurs here
    Py_XDECREF(pval);
               ^~~~
/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/object.h:571:51: note: expanded from macro 'Py_XDECREF'
#define Py_XDECREF(op) _Py_XDECREF(_PyObject_CAST(op))
                                                  ^~
/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/object.h:112:41: note: expanded from macro '_PyObject_CAST'
#define _PyObject_CAST(op) ((PyObject*)(op))
                                        ^~
easysnmp/interface.c:4114:36: note: initialize the variable 'pval' to silence this warning
    PyObject *log_msg = NULL, *pval;
                                   ^
                                    = NULL
In file included from easysnmp/interface.c:48:
easysnmp/simple_bitarray.h:247:13: warning: unused function 'wno_unused_function_simple_bitarray_h' [-Wunused-function]
static void wno_unused_function_simple_bitarray_h(void)
            ^
easysnmp/interface.c:1440:14: warning: unused function 'py_netsnmp_attr_void_ptr' [-Wunused-function]
static void *py_netsnmp_attr_void_ptr(PyObject *obj, char *attr_name)
             ^
10 warnings generated.
In file included from easysnmp/interface.c:48:
easysnmp/simple_bitarray.h:116:29: warning: variable 'nbytes' is used uninitialized whenever 'for' loop exits because its condition is false [-Wsometimes-uninitialized]
            for (i = nbits; i > (nbits - remaining_bits); i--)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/simple_bitarray.h:122:27: note: uninitialized use occurs here
        memset(&ba[1], 0, nbytes);
                          ^~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:77:33: note: expanded from macro 'memset'
                __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                              ^~~~~~~~~~~
easysnmp/simple_bitarray.h:116:29: note: remove the condition if it is always true
            for (i = nbits; i > (nbits - remaining_bits); i--)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/simple_bitarray.h:98:22: note: initialize the variable 'nbytes' to silence this warning
        size_t nbytes;
                     ^
                      = 0
easysnmp/interface.c:500:21: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
            if (len > buf_len)
                ~~~ ^ ~~~~~~~
easysnmp/interface.c:1260:40: warning: comparison of integers of different signs: 'unsigned long' and 'long' [-Wsign-compare]
                else if (last_errindex > (*response)->errindex)
                         ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:2407:55: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
        if (snmp_version == 1 && DEFAULT_NUM_BAD_OIDS < varlist_len)
                                 ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~
easysnmp/interface.c:2894:44: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                    if ((vars->name_length < oid_arr_len[varlist_ind]) ||
                         ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:3650:48: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                        if ((vars->name_length < oid_arr_len[varlist_ind]) ||
                             ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:3975:28: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'unsigned long' [-Wsign-compare]
                if (tmplen >= sizeof(tmp_val_str))
                    ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
easysnmp/interface.c:4152:5: warning: variable 'pval' is used uninitialized whenever switch default is taken [-Wsometimes-uninitialized]
    default:
    ^~~~~~~
easysnmp/interface.c:4158:16: note: uninitialized use occurs here
    Py_XDECREF(pval);
               ^~~~
/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/object.h:571:51: note: expanded from macro 'Py_XDECREF'
#define Py_XDECREF(op) _Py_XDECREF(_PyObject_CAST(op))
                                                  ^~
/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/object.h:112:41: note: expanded from macro '_PyObject_CAST'
#define _PyObject_CAST(op) ((PyObject*)(op))
                                        ^~
easysnmp/interface.c:4114:36: note: initialize the variable 'pval' to silence this warning
    PyObject *log_msg = NULL, *pval;
                                   ^
                                    = NULL
In file included from easysnmp/interface.c:48:
easysnmp/simple_bitarray.h:247:13: warning: unused function 'wno_unused_function_simple_bitarray_h' [-Wunused-function]
static void wno_unused_function_simple_bitarray_h(void)
            ^
easysnmp/interface.c:1440:14: warning: unused function 'py_netsnmp_attr_void_ptr' [-Wunused-function]
static void *py_netsnmp_attr_void_ptr(PyObject *obj, char *attr_name)
             ^
10 warnings generated.
clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-3.10/easysnmp/interface.o -L/usr/local/opt/net-snmp/lib -L/usr/local/opt/openssl@1.1/lib -lnetsnmp -o build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so
ld: warning: ignoring file /usr/local/opt/net-snmp/lib/libnetsnmp.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: dylib (/usr/local/opt/net-snmp/lib/libnetsnmp.dylib) was built for newer macOS version (12.0) than being linked (10.9)
creating build/bdist.macosx-10.9-universal2
creating build/bdist.macosx-10.9-universal2/egg
creating build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/compat.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/variables.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/session.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/__init__.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/easy.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/utils.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/exceptions.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/helpers.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/compat.py to compat.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/variables.py to variables.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/session.py to session.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/easy.py to easy.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/utils.py to utils.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/exceptions.py to exceptions.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/helpers.py to helpers.cpython-310.pyc
creating stub loader for easysnmp/interface.cpython-310-darwin.so
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/interface.py to interface.cpython-310.pyc
creating build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/PKG-INFO -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/top_level.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
writing build/bdist.macosx-10.9-universal2/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
easysnmp.__pycache__.interface.cpython-310: module references __file__
creating dist
creating 'dist/easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg' and adding 'build/bdist.macosx-10.9-universal2/egg' to it
removing 'build/bdist.macosx-10.9-universal2/egg' (and everything under it)
Processing easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg
creating /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg
Extracting easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Adding easysnmp 0.2.6a1 to easy-install.pth file

Installed /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg
Processing dependencies for easysnmp==0.2.6a1
Finished processing dependencies for easysnmp==0.2.6a1
test@C02DG9X7MD6R easysnmp % otool -L build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so
build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so:
	/usr/local/opt/net-snmp/lib/libnetsnmp.40.dylib (compatibility version 42.0.0, current version 42.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

**Comment by joseftschiggerlnts** [comment]
test@C02DG9X7MD6R easysnmp % python3.10 setup.py install                                                            
/Users/test/Downloads/test/easysnmp/setup.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils import sysconfig
/Users/test/Downloads/test/easysnmp/setup.py:5: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils import sysconfig
running install
running bdist_egg
running egg_info
writing easysnmp.egg-info/PKG-INFO
writing dependency_links to easysnmp.egg-info/dependency_links.txt
writing top-level names to easysnmp.egg-info/top_level.txt
reading manifest file 'easysnmp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'easysnmp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-universal2/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.9-universal2/egg
creating build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/compat.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/variables.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/session.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/__init__.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/easy.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/utils.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/exceptions.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
copying build/lib.macosx-10.9-universal2-3.10/easysnmp/helpers.py -> build/bdist.macosx-10.9-universal2/egg/easysnmp
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/compat.py to compat.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/variables.py to variables.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/session.py to session.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/easy.py to easy.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/utils.py to utils.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/exceptions.py to exceptions.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/helpers.py to helpers.cpython-310.pyc
creating stub loader for easysnmp/interface.cpython-310-darwin.so
byte-compiling build/bdist.macosx-10.9-universal2/egg/easysnmp/interface.py to interface.cpython-310.pyc
creating build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/PKG-INFO -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying easysnmp.egg-info/top_level.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
writing build/bdist.macosx-10.9-universal2/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
easysnmp.__pycache__.interface.cpython-310: module references __file__
creating 'dist/easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg' and adding 'build/bdist.macosx-10.9-universal2/egg' to it
removing 'build/bdist.macosx-10.9-universal2/egg' (and everything under it)
Processing easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg
creating /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg
Extracting easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Adding easysnmp 0.2.6a1 to easy-install.pth file

Installed /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/easysnmp-0.2.6a1-py3.10-macosx-10.9-universal2.egg
Processing dependencies for easysnmp==0.2.6a1
Finished processing dependencies for easysnmp==0.2.6a1
test@C02DG9X7MD6R easysnmp % otool -L build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so
build/lib.macosx-10.9-universal2-3.10/easysnmp/interface.cpython-310-darwin.so:
	/usr/local/opt/net-snmp/lib/libnetsnmp.40.dylib (compatibility version 42.0.0, current version 42.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

**Comment by kamakazikamikaze** [comment]
Hm. So cloning the repo and installing manually worked perfectly fine and linked the shared library object just fine.

Do you get any errors running the code?

**Comment by kamakazikamikaze** [comment]
If you don't encounter errors, I'd like to ask that you issue a `pip remove easysnmp` and then `pip install .` to determine if pip itself is the issue

**Comment by joseftschiggerlnts** [comment]
ha! it works :)
Well that is very strange ... I will dig into this further to see why the other approach didn't work out.

Anyway, for the application I will just wait for the new release via pip instead of building it :) 

Thanks a lot!

**Comment by kamakazikamikaze** [comment]
Please do check it out and let me know. macOS is the trickier OS to get right since Brew is involved and is not possible for me to virtualize for testing different scenarios. I'll take all the help I can get with it!

**Comment by joseftschiggerlnts** [comment]
I will test it, yes.
Please do let me know If I can help you testing anything. I will be working with easysnmp (and snmp in general) quite a lot in the near future :)

**Comment by joseftschiggerlnts** [comment]
solved
