### ISSUE TITLE
[BUG] update_session not working for snmp v3

### ISSUE THREAD

**Issue by joseftschiggerlnts** [easysnmp/easysnmp#156]
**EasySNMP release version OR commit number**
Installed directly via git (git clone https://github.com/kamakazikamikaze/easysnmp.git), "pip install ."

**Operating System and Version**
 - OS: macOS
 - Version 12.4

**Net-SNMP Library Version**
 - 5.9.1 (via brew)

**Python**
 - python3.10

**Describe the bug**
I want to updaten an existing snmpv3 session and change e.g. security_level, security_username, auth_password, ...

**To Reproduce**
```
def prep_snmpv3_credentials(cs:dict)->dict:
        snmpopts={}
        snmpopts['security_username'] = cs.split()[0]
        snmpopts['auth_protocol'] = cs.split()[1].upper()
        snmpopts['auth_password'] = cs.split()[2]
        snmpopts['privacy_protocol'] = cs.split()[3].lower()
        snmpopts['privacy_password'] = cs.split()[4]

        if snmpopts['privacy_protocol'] == 'nopriv':
            snmpopts['security_level'] = 'auth_without_privacy'
            snmpopts['privacy_protocol'] = 'DEFAULT'
        else:
            snmpopts['security_level'] = 'auth_with_privacy'

        if snmpopts['privacy_protocol'] == 'aes128':
            snmpopts['privacy_protocol'] = 'AES'

        return snmpopts

def main():
    cs=['username sha asdf aes128 qwert','username sha asdf aes128 qwer']
    session = easysnmp.Session(hostname='172.21.22.23',
                                    version=3,
                                    timeout=1,
                                    retries=1,
                                    use_long_names=True,
                                    abort_on_nonexistent=True)
    for i in cs:
        allopts = prep_snmpv3_credentials(i)
        try:
            sysdescr=""
            session.update_session(security_level=allopts['security_level'],
                                    security_username=allopts['security_username'],
                                    auth_protocol=allopts['auth_protocol'],
                                    auth_password=allopts['auth_password'],
                                    privacy_protocol=allopts['privacy_protocol'],
                                    privacy_password=allopts['privacy_password'],)
            sysdescr = session.get('1.3.6.1.2.1.1.1.0').value
        except Exception as e:
            print(e)
        print(sysdescr)
    print("final")
```

Both runs of the loop return a valid sysdescr, if I swap the list entries, then both loop runs return "auth failed"

**Expected behavior**
First run of the for loop returns sysdescr, second run fails with "authentication failed"

**Comment by joseftschiggerlnts** [comment]
Note, doing the same (eg. updating the community string) with snmp 2 works as expected

**Comment by joseftschiggerlnts** [comment]
Hey @kamakazikamikaze 
Would you be able to confirm if this is indeed a bug in easysnmp?
I looked into the source myself but couldnt really figure it out ... It might be that snmpv3 is encrypted and certain parts of the connection can not be updated easily because of this?

thanks

**Comment by kamakazikamikaze** [comment]
Confirmed it's a bug. Will investigate.

**Comment by kamakazikamikaze** [comment]
Did some quick checking and ruled out the issue being caused by our `Session`. It may instead be due to the user info being cached by the Net-SNMP library. While clever, this is inconvenient for us where a username and password combo changes between devices.

Source: https://stackoverflow.com/a/18466181

**Comment by kamakazikamikaze** [comment]
Confirmed that clearing users from the USM cache list fixes the issue. Fixing this isn't completely trivial. We don't want to completely clear out the list of users each time a new session is made, nor when one is destroyed.
