### ISSUE TITLE
ImportError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by rfonacier** [easysnmp/easysnmp#61]
I have a MySQL running already on my Raspberry Pi.  I have created a DB and tables in it.
On python program, I tried to connect to it but I got this error.

![image](https://cloud.githubusercontent.com/assets/26764469/26042366/cc307c6a-3945-11e7-9a92-260888eaa0e9.png)

**Comment by kamakazikamikaze** [comment]
@rfonacier, I'm afraid that the issue tracker here is for questions regarding the easysnmp library. We cannot help you with questions/problems in trying to get code working for other projects. If you need assistance, I would recommend posting at help sites like StackOverflow.com or www.reddit.com/r/learnprogramming

Sorry! :)
