### ISSUE TITLE
Release v0.2.5 update

### ISSUE THREAD

**Issue by kamakazikamikaze** [easysnmp/easysnmp#63]
Since v0.2.4, a handful of small and large updates have been pulled into the project. `bulkwalk` is the most notable addition with memory leak patches following just behind it.

While this series of tests is overkill, I want to be *very certain* that my changes will not break existing code, nor introduce additional leaks. Python 3 behavior appears to be fine, however Python 2 seems to still have some odd reports — of which I cannot determine if it is normal or not. This is all to ensure that we will not break anyone's projects that are in production.

Due to some of the code refactoring, and the addition of OS X/macOS `brew` support, I would like to perform some intensive and thorough tests before proceeding:

Platform | Py Version | Test | Description
---------|------------|-----|------------
Mint 18 | 2.7.x | Memory Leak Checks | Frequent equipment polling will take place. No manual GC calls. 4GB RAM will be dedicated to the system. Run for 48 hours; check memory usage and monitor for system failure due to exhausted RAM
Mint 18 | 3.x | Memory Leak Checks | Frequent equipment polling will take place. No manual GC calls. 4GB RAM will be dedicated to the system. Run for 48 hours; check memory usage and monitor for system failure due to exhausted RAM
OS X El Capitan | 2.7.x | Memory Leak Checks | Frequent equipment polling will take place. No manual GC calls. 8 GB RAM will be dedicated to the system. Run for 48 hours; check memory usage and monitor for system failure due to exhausted RAM
mac OS Sierra | 3.x | Memory Leak Checks | Frequent equipment polling will take place. No manual GC calls. 8 GB RAM will be dedicated to the system. Run for 48 hours; check memory usage and monitor for system failure due to exhausted RAM
Ubuntu 14.04 LTS | 2.7.x | Memory Leak Checks | A Raspberry Pi will be set up and will be used for testing errors. A lot of `set` and `walk` calls will be done on bad OIDs. This will check if PDUs are being released properly in all scenarios. Valid OIDs will also be checked.

Tests will be conducted on Cisco C3560CG, C3750V2, and C3650X models.

Due to time constraints I will be out this weekend, so testing the Pi will be the first to run.

**v0.2.5 will be released no later than June 10th**

**Comment by nnathan** [comment]
Just going to say, this is impressive.

On a side note: I'm not sure how Fotis configured the project but I'm apprised of all issues (even though I'm no longer involved with easysnmp). Do you know how to unsubscribe me from being notified of the issues?

Thanks and keep up the good work!

**Comment by kamakazikamikaze** [comment]
Oh, hey @nnathan! Are you Watching the package? Perhaps setting it to Not Watching or Ignore will fix this for you.

Also, thank you for your work in getting this project up and running, as well as your efforts in adding the PyCapsule/CObject code. It was really helpful in getting v0.2.5 rolling.

**Comment by nnathan** [comment]
Thanks for the hint, I unwatched myself!

As I've progressed as a C programmer, I know for all the snmp operations, you should just allocate a buffer on the stack for 64KB (max size for an SNMP packet), this way you don't have to worry about heap allocation/release which is messy & slow. My original motivation was to avoid heap allocations using pycapsules, but it now dawned on me that you should avoid heap allocations altogether (you might have to convince yourself of that of course :)).

I'm glad some of my work was found useful. There's a lot that needs to be done in the C side of things, especially if you can get something like automated benchmarks and leak detection as part of the CI.

In any case, long gone are the days I need to use SNMP. I wish you the best of luck, and I sincerely hope the work @fgimian has put into this package has found good use.

Thanks again.

**Comment by kamakazikamikaze** [comment]
Update to be released today! Sorry for missing the deadline, had an emergency that required flying out of state.

Unfortunately, the test suite does not work the same on some OS as it does on others; the SNMP values on Raspbian Jessie do not match those from Ubuntu 14.04 and Mint 18. As such, I cannot verify that they work properly on _all_ Linux distros just yet.

However, I was still able to do tests on other machines and review the amount of memory being used by each. Valgrind reports that we are not experiencing leaks. Python 2 will retain its memory footprint, however Python 3 seems to continually grow (though slowly). I cannot determine if this is an issue with the GC or in the C code. I will continue to look into it.
