### ISSUE TITLE
support macports on OSX

### ISSUE THREAD

**Issue by petri** [easysnmp/easysnmp#66]
besides homebrew, net-snmp is also available on macports on OSX

**Comment by petri** [comment]
ok I wrongly thought it was not supported because setup.py only listed homebrew... my bad, sorry for the trouble, move on nothing to see here...

**Comment by kamakazikamikaze** [comment]
Petri, do you encounter any errors when installing Net-SNMP via Macports? Perhaps I'll mention the compatibility in a future documentation update so that the information is readily available :)

**Comment by kamakazikamikaze** [comment]
And by errors I mean errors installing EasySNMP with Net-SNMP from Macports. I don't need to know about errors installing Net-SNMP itself 😅

**Comment by petri** [comment]
No, I did not encounter any errors whatsoever. I am on OSX El Capitan (10.11.6), running Python 3.6.0. 

Thank you for your work on the package! :) I agree that adding a note about supporting both homebrew and macports would be a good idea.
